name: Markdown link check

# When this workflow triggers
on:
  push:
  workflow_dispatch:

# Job definition
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.mlc-config.json'
        folder-path: '.'
        max-depth: -1